### ISSUE TITLE
Detect when recursive spider is done

### ISSUE THREAD

**Issue by lukasoppermann** [missinglink/huntsman#21]
Hey, very nice spider.

One question though: Is there a way I can know that the spider is done when using the recursive plugin? I want to use this in gulp, so I need to call know when the links stop coming in.

Okay, I am actually using the links plugin now, but it is the same problem. I want to do something like this, but the links array is empty, because the spider is async.

```js
let crawl = function (url) {
  let huntsman = require('huntsman')
  let spider = huntsman.spider()
  let links = []
  spider.extensions = [
    huntsman.extension( 'links' )
  ]

  spider.on( '/', function ( err, res ){

  if( !res.extension.links ) return; // content is not a string

  links = res.extension.links({
    pattern: {
      search: /<a([^>]+)href\s?=\s?['"]([^"'#]+)/gi,
      refine: /['"]([^"'#]+)$/,
      filter: new RegExp(url)
    }
  });

});

  spider.queue.add(url)
  spider.start()

  return links

}
```

Thanks.

**Comment by missinglink** [comment]
hi @lukasoppermann, the spider emits events as per https://github.com/missinglink/huntsman/pull/13

> so I need to call know when the links stop coming in

you probably want to know when the **last link has been processed** rather than when **links stop coming in**

for this, you can listen for the `HUNTSMAN_EXIT` event or simply wait for the process to exit.

**Comment by missinglink** [comment]
also, regarding your code, changing your code to something like this might help:

```
links = xxx

vs..

links = links.concat( xxx )
```

**Comment by lukasoppermann** [comment]
Hey, thanks.

Sadly I am not able to get all this put together correctly. I am trying to gather all links to put them into `postcss-uncss`.

My current approach is the:
1. function above
2. call this function within a gulp task to get the links
3. run the post-css stuff

However I have 2 issues:
1. I don't know what you mean with `links = links.concat( xxx )` could you please elaborate? 
2. The task moves on before the spider is done, I get this:

> [13:31:46] Using gulpfile ~/Code/veare/gulpfile.js
> [13:31:46] Starting 'build-css'...
> [13:31:47] CSS:  19% saved  Total size 76.7 kB / 11.93 kB (gzip)
> [13:31:47] Finished 'build-css' after 1.62 s
> spider stop
> []

Does that have to do with the `links.concat`? Or am I missing something else? Thank you for your help.

**Comment by missinglink** [comment]
ok, I think I understand

looking at your code:

```
let crawl = function (url) {
  let links = [];
  doSomeThingAync();
  return links;
}
```

`links` will be returned immediately, so it's always going to be empty.
The async function will not block script execution like it would in another language, you'll need to avoid using the `return` keyword.

try refactoring your code to work on callback, such as:

```
let crawl = function (url, callback) {
  let links = [];
  doSomeThingAync( callback );
}
```

or more specifically for this usecase it would look something like this:

```
let crawl = function (url, callback) {
  
  let huntsman = require('huntsman')
  let spider = huntsman.spider()
  let links = []
  spider.extensions = ... your extensions here

  spider.on( '/', function ( err, res ) ... your code goes here

  // this is the important bit
  spider.on( 'HUNTSMAN_EXIT', function(){
    callback( null, links );
  });

  spider.queue.add(url)
  spider.start()
}
```

then when you execute the function you can pass a callback function which only executes once the spider has completed:

```
crawl( 'http://foo.com', function( err, links ){
  console.log( links );
});
```

this is the 'standard node way' of handling async code.

in regards to `links.concat`, I simply mean that you likely want to `append` to the array rather than `replace` the array each time you hit a URL. this depends on what you're trying to achieve.

all the best

**Comment by lukasoppermann** [comment]
Way to be stupid. 😖  Thanks a lot, I did try something similar but must have done something wrong. Works like a charm now, also thank you for the hint with `links.concat`!  👍 

Thank you for your nice and very fast support.

One last question though: Is there a reason why `HUNTSMAN_EXIT` is not in the docs? Or did I just not find it. 😃

**Comment by missinglink** [comment]
I'm not sure why it never made it in to the docs...

Happy to help :)
